// Analyzes a journal transcript: classifies crisis risk, extracts theme tags,
// retrieves a matching dua/verse/hadith + istighfar from our own vetted content
// table (never AI-generated scripture), and drafts a short reflection.
//
// theme_tags/crisis_flag are derived here and written with the service role key —
// the client is never granted UPDATE on those columns (see migrations), so a
// compromised client can't spoof a "safe" classification.
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { getEntitlement } from "../_shared/entitlement.ts";

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, apikey, content-type",
};

const THEME_TAXONOMY = [
  "anxiety", "grief", "marriage", "workplace", "faith-doubt",
  "gratitude", "immigration-family", "financial-stress", "loneliness", "anger",
];

// Deterministic safety net, checked BEFORE Claude's classification. Testing
// showed Claude's crisis classification is not perfectly consistent across
// calls even on clearly suicidal input — a single probabilistic call is not
// reliable enough as the only line of defense here. Any of these phrases
// forces crisis_flag=true regardless of what the model would have said.
// English-only for now; non-English or non-matching crisis language still
// falls through to Claude's classification below.
const CRISIS_KEYWORDS = [
  /kill(ing)? myself/i, /end(ing)? my life/i, /suicid(e|al)/i,
  /want(ing)? to die/i, /no (reason|point) (to|in) (liv(e|ing)|going on)/i,
  /(hurt|harm)(ing)? myself/i, /self[- ]harm/i, /better off dead/i,
  /don'?t want to (be here|exist) anymore/i,
];
function matchesCrisisKeywords(text: string): boolean {
  return CRISIS_KEYWORDS.some((re) => re.test(text));
}

type Candidate = { id: string; type: string; translation: string; theme_tags: string[] };

// Builds the system prompt fresh per request so the candidate list (and the
// schema enum built from it) always reflects the live content_items table —
// no redeploy needed when content is added/edited.
//
// Hadith/dua are still matched only against our own pre-verified table (kept
// deliberately small so every entry in it has been checked against a live
// source before insertion). Quran verses instead let Claude pick ANY surah:ayah
// across all 114 surahs by reference — the actual Arabic/translation text is
// never generated by Claude itself, it's fetched separately from a verified
// external Quran API once Claude names the reference. This is what makes full-
// Quran coverage possible without expanding an ever-growing hand-curated table,
// while keeping the original guarantee: the model never renders scripture text.
function buildSystemPrompt(candidates: Candidate[]): string {
  const candidateList = candidates
    .map((c) => `- id="${c.id}" (${c.type}, tags: ${c.theme_tags.join(", ") || "none"}): "${c.translation}"`)
    .join("\n");
  return `You are a careful classifier and reflection-writer for a Muslim voice-journaling app.
You NEVER quote, paraphrase, or invent Quran verses or hadith text yourself — the app supplies verified
content separately. Your jobs, given a journal transcript, are:

1. Decide if this entry is a crisis: crisis_flag is true ONLY for explicit or strongly implied suicidal
   ideation, self-harm intent, ongoing abuse, or immediate physical danger.
   crisis_flag is FALSE for ordinary stress, anxiety, sadness, anger, guilt, or frustration about everyday
   life — exams, work, deadlines, marriage friction, money worries, grief, loneliness — even when the person
   expresses strong or intense emotion about it. Emotional intensity alone is never sufficient; you need a
   concrete signal of intent to harm someone (including themselves) or an active dangerous situation.
   Examples that are FALSE: "I'm so anxious about this exam I can't focus", "I'm furious at my coworker",
   "I feel like such a failure", "I'm devastated about my divorce".
   Examples that are TRUE: "I've been thinking about ending my life", "he hits me and I'm scared to go home",
   "I don't want to be alive anymore".
   When genuinely unsure between an intense-but-ordinary feeling and a real crisis signal, prefer FALSE —
   a separate deterministic keyword check already catches the clearest crisis language before this
   classification ever runs, so your job here is to catch subtler true crises without over-flagging.
2. Pick 1-3 theme tags that best fit, ONLY from this fixed list: ${THEME_TAXONOMY.join(", ")}.
3. Choose the SINGLE best-fitting piece of content for this specific situation — either a hadith/dua from
   the list below (via content_item_id), OR a Quran verse from anywhere across all 114 surahs (via
   quran_surah/quran_ayah_start/quran_ayah_end), never both. Prefer whichever genuinely fits better; don't
   default to Quran just because it's available, and don't stretch a weak match just to fill the field —
   leave everything null if genuinely nothing fits well.
   - content_item_id: pick by id from this exact list, based on each item's actual translation, not just
     shared tags (two items can share a tag and differ hugely in fit):
${candidateList}
   - quran_surah (1-114) / quran_ayah_start / quran_ayah_end: set all three together, or leave all three
     null. quran_ayah_end must equal quran_ayah_start or be at most 2 ayahs later (keep excerpts short and
     focused). Choose based on your own knowledge of the Quran, picking the specific ayah(s) whose PLAIN
     MEANING is directly comforting, reflective, or instructive for someone going through this — not a
     passage that's primarily legal, genealogical, or narrative/historical with no direct bearing on
     personal emotional hardship. Be exact about the reference; if you are not confident of the precise
     surah/ayah number, leave these null instead of guessing.
4. Write a warm, non-preachy reflection (3-5 sentences) acknowledging the specific situation the person
   described, and — if you picked a content_item_id or a Quran reference — explain in your own words why
   that particular verse/hadith/dua speaks to it. Do not quote or paraphrase its Arabic/translation text
   directly (the app displays that separately below your reflection, fetched from its own verified source);
   refer to it only in general terms (e.g. "the reflection below on patience..."). Do not give religious
   rulings or claim authority you don't have.
Respond ONLY with JSON: {"crisis_flag": boolean, "theme_tags": string[], "content_item_id": string|null, "quran_surah": number|null, "quran_ayah_start": number|null, "quran_ayah_end": number|null, "reflection": string}`;
}

// Fetches verified Arabic (Uthmani script) + English (Sahih International)
// text for a short ayah range from a public Quran API — this, never Claude's
// own rendering, is the actual source of truth for verse text shown to users.
// Returns null on any validation/fetch failure so the caller can just fall
// back to "no verse matched" rather than surfacing bad data.
async function fetchQuranVerse(
  surah: number, ayahStart: number, ayahEnd: number,
): Promise<{ arabic_text: string; translation: string; source: string } | null> {
  if (!Number.isInteger(surah) || surah < 1 || surah > 114) return null;
  if (!Number.isInteger(ayahStart) || ayahStart < 1) return null;
  if (!Number.isInteger(ayahEnd) || ayahEnd < ayahStart || ayahEnd - ayahStart > 2) return null;

  // Fetch every ayah's Arabic+English in parallel (not one ayah at a time) —
  // this endpoint has no multi-ayah range lookup, and a 3-ayah pick was taking
  // up to 6 sequential round-trips, adding enough latency to occasionally
  // cause the client's connection to drop before any response came back.
  const ayahNumbers = Array.from({ length: ayahEnd - ayahStart + 1 }, (_, i) => ayahStart + i);
  const results = await Promise.all(
    ayahNumbers.map(async (ayah) => {
      const [arRes, enRes] = await Promise.all([
        fetch(`https://api.alquran.cloud/v1/ayah/${surah}:${ayah}/quran-uthmani`),
        fetch(`https://api.alquran.cloud/v1/ayah/${surah}:${ayah}/en.sahih`),
      ]);
      if (!arRes.ok || !enRes.ok) return null;
      const [arData, enData] = await Promise.all([arRes.json(), enRes.json()]);
      if (arData.code !== 200 || enData.code !== 200 || !arData.data?.text || !enData.data?.text) return null;
      return { arabic: arData.data.text as string, translation: enData.data.text as string };
    }),
  );
  if (results.some((r) => r === null)) return null;
  const verified = results as { arabic: string; translation: string }[];
  return {
    arabic_text: verified.map((r) => r.arabic).join(" "),
    translation: verified.map((r) => r.translation).join(" "),
    source: `Quran ${surah}:${ayahStart}${ayahEnd > ayahStart ? `-${ayahEnd}` : ""}`,
  };
}

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: CORS_HEADERS });

  const authHeader = req.headers.get("Authorization") || "";
  const token = authHeader.replace("Bearer ", "");
  const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
  const SERVICE_ROLE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
  const ANTHROPIC_KEY = Deno.env.get("ANTHROPIC_API_KEY");

  if (!token) {
    return new Response(JSON.stringify({ error: "Missing Authorization header" }), {
      status: 401, headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  }
  if (!ANTHROPIC_KEY) {
    return new Response(JSON.stringify({ error: "Analysis is not configured yet." }), {
      status: 500, headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  }

  // Resolve the caller's user id from their access token.
  const userRes = await fetch(`${SUPABASE_URL}/auth/v1/user`, {
    headers: { Authorization: `Bearer ${token}`, apikey: SERVICE_ROLE_KEY },
  });
  if (!userRes.ok) {
    return new Response(JSON.stringify({ error: "Invalid session" }), {
      status: 401, headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  }
  const user = await userRes.json();

  const { transcript, language, entry_type } = await req.json();
  const entryType = entry_type === "text" ? "text" : "voice";
  if (!transcript || typeof transcript !== "string") {
    return new Response(JSON.stringify({ error: "Missing transcript" }), {
      status: 400, headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
    });
  }

  let parsed: {
    crisis_flag: boolean; theme_tags: string[]; content_item_id: string | null;
    quran_surah: number | null; quran_ayah_start: number | null; quran_ayah_end: number | null;
    reflection: string;
  };
  let candidates: Candidate[] = [];

  if (matchesCrisisKeywords(transcript)) {
    // Deterministic match — skip the model call entirely. The crisis screen
    // doesn't use theme_tags/content/reflection, and there's no reason to give
    // a probabilistic classifier a chance to talk this back down.
    parsed = {
      crisis_flag: true, theme_tags: [], content_item_id: null,
      quran_surah: null, quran_ayah_start: null, quran_ayah_end: null, reflection: "",
    };
  } else {
    // Fetch the hadith/dua candidate pool up front so Claude can pick the
    // single best-fitting item by actually reading each one, rather than us
    // doing a blind "first row sharing a tag" SQL query after the fact — with
    // a small library, several items can share a tag and differ hugely in fit.
    // Quran verses are handled separately (see quran_reference below) since
    // Claude can pick from all 114 surahs, not just a hand-curated subset.
    const candidatesRes = await fetch(
      `${SUPABASE_URL}/rest/v1/content_items?type=in.(hadith,dua)&select=id,type,arabic_text,translation,source,theme_tags`,
      { headers: { apikey: SERVICE_ROLE_KEY, Authorization: `Bearer ${SERVICE_ROLE_KEY}` } },
    );
    const candidateRows = await candidatesRes.json();
    candidates = Array.isArray(candidateRows) ? candidateRows : [];

    // Plaintext transcript is used only transiently here (in memory, this call) —
    // it is never logged or persisted; the client encrypts it before storage.
    const claudeRes = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": ANTHROPIC_KEY,
        "anthropic-version": "2023-06-01",
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        model: "claude-sonnet-5",
        max_tokens: 600,
        system: buildSystemPrompt(candidates),
        messages: [{ role: "user", content: transcript }],
        // Structured outputs guarantee schema-conforming JSON — more reliable
        // than a "respond only with JSON" instruction, which can occasionally
        // get wrapped in preamble text or omit a field.
        output_config: {
          format: {
            type: "json_schema",
            schema: {
              type: "object",
              properties: {
                crisis_flag: { type: "boolean" },
                theme_tags: { type: "array", items: { type: "string", enum: THEME_TAXONOMY } },
                content_item_id: { type: ["string", "null"], enum: [...candidates.map((c) => c.id), null] },
                // Flat nullable primitives, not a nested nullable object. A previous
                // version used a nested {type:["object","null"], required:[...]} shape
                // for this, which is suspected (not yet confirmed) to have made every
                // response fail schema validation. This flatter shape mirrors
                // content_item_id's already-proven-working nullable pattern instead.
                quran_surah: { type: ["integer", "null"], minimum: 1, maximum: 114 },
                quran_ayah_start: { type: ["integer", "null"], minimum: 1 },
                quran_ayah_end: { type: ["integer", "null"], minimum: 1 },
                reflection: { type: "string" },
              },
              required: [
                "crisis_flag", "theme_tags", "content_item_id",
                "quran_surah", "quran_ayah_start", "quran_ayah_end", "reflection",
              ],
              additionalProperties: false,
            },
          },
        },
      }),
    });

    if (!claudeRes.ok) {
      const errText = await claudeRes.text();
      console.error("Claude analysis failed:", errText);
      return new Response(JSON.stringify({ error: "Could not analyze entry" }), {
        status: 502, headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
      });
    }

    const claudeData = await claudeRes.json();
    try {
      const textBlock = claudeData.content?.find((b: { type: string }) => b.type === "text");
      if (!textBlock) throw new Error("No text block in Claude response");
      parsed = JSON.parse(textBlock.text);
    } catch (e) {
      // Fail closed: if we can't parse the model's classification, treat it
      // as a possible crisis rather than silently defaulting to "safe".
      // Log response shape (never the transcript/reflection text) so a bad
      // fallback here is diagnosable instead of silent.
      console.error(
        "Failed to parse Claude classification:",
        String(e),
        "stop_reason:", claudeData.stop_reason,
        "content block types:", claudeData.content?.map((b: { type: string }) => b.type),
      );
      parsed = {
        crisis_flag: true, theme_tags: [], content_item_id: null,
        quran_surah: null, quran_ayah_start: null, quran_ayah_end: null, reflection: "",
      };
    }
  }
  const themeTags = (parsed.theme_tags || []).filter((t) => THEME_TAXONOMY.includes(t));

  // Authoritative enforcement point for the freemium limit — checked AFTER
  // crisis classification, and only enforced when this is NOT a crisis.
  // Blocking a genuine crisis behind a paywall would be actively harmful, so
  // the cost of classifying an over-limit user's entry is accepted as the
  // price of never doing that. (check-entitlement is the client-side
  // pre-check that saves this cost in the common, non-crisis case.)
  if (!parsed.crisis_flag) {
    const entitlement = await getEntitlement(SUPABASE_URL, SERVICE_ROLE_KEY, user.id);
    if (!entitlement.allowed) {
      return new Response(JSON.stringify({ limit_reached: true, ...entitlement }), {
        status: 402, headers: { ...CORS_HEADERS, "Content-Type": "application/json" },
      });
    }
  }

  let content: { id?: string; arabic_text: string; translation: string; source: string } | null = null;
  let quranContent: { arabic_text: string; translation: string; source: string } | null = null;
  let istighfar = null;

  if (!parsed.crisis_flag) {
    // Claude already picked the best-fitting hadith/dua id from the exact
    // candidates it was shown above — just look it up locally, no extra query.
    content = candidates.find((c) => c.id === parsed.content_item_id) || null;
    // The Quran-verse fetch and the istighfar lookup are independent of each
    // other — run them concurrently rather than one after the other, same
    // latency reasoning as fetchQuranVerse's internal parallelization above.
    const wantsQuranFetch = !content && parsed.quran_surah && parsed.quran_ayah_start && parsed.quran_ayah_end;
    const [quranResult, istighfarRows] = await Promise.all([
      wantsQuranFetch
        ? fetchQuranVerse(parsed.quran_surah!, parsed.quran_ayah_start!, parsed.quran_ayah_end!)
        : Promise.resolve(null),
      fetch(`${SUPABASE_URL}/rest/v1/content_items?type=eq.istighfar`, {
        headers: { apikey: SERVICE_ROLE_KEY, Authorization: `Bearer ${SERVICE_ROLE_KEY}` },
      }).then((r) => r.json()),
    ]);
    // If it picked a Quran reference instead, fetch the real verified text —
    // never trust the model's own rendering of Arabic scripture. Falls back
    // to null (not an error) if the reference is invalid or the API is down,
    // same "just don't show a match" degradation as any other empty result.
    // Tracked separately from `content` so the DB insert below knows which of
    // content_item_id (a real FK) vs quran_* (a text snapshot) to fill in.
    if (wantsQuranFetch) {
      quranContent = quranResult;
      content = quranContent;
    }
    // PostgREST's order= param only accepts column names, not function calls
    // like random() — fetch the small istighfar set and pick one client-side.
    istighfar = Array.isArray(istighfarRows) && istighfarRows.length > 0
      ? istighfarRows[Math.floor(Math.random() * istighfarRows.length)]
      : null;
  }

  // Insert the row now (service role) with the AI-derived fields locked in;
  // the client will PATCH in only the encrypted_transcript afterward.
  const insertRes = await fetch(`${SUPABASE_URL}/rest/v1/journal_entries`, {
    method: "POST",
    headers: {
      apikey: SERVICE_ROLE_KEY, Authorization: `Bearer ${SERVICE_ROLE_KEY}`,
      "Content-Type": "application/json", Prefer: "return=representation",
    },
    body: JSON.stringify({
      user_id: user.id,
      language_detected: language || null,
      theme_tags: themeTags,
      crisis_flag: !!parsed.crisis_flag,
      reflection: parsed.reflection || "",
      content_item_id: content?.id ?? null,
      quran_arabic_text: quranContent?.arabic_text ?? null,
      quran_translation: quranContent?.translation ?? null,
      quran_source: quranContent?.source ?? null,
      istighfar_item_id: istighfar?.id ?? null,
      entry_type: entryType,
    }),
  });
  const inserted = await insertRes.json();
  const entryId = Array.isArray(inserted) ? inserted[0]?.id : null;

  return new Response(
    JSON.stringify({
      entry_id: entryId,
      crisis_flag: !!parsed.crisis_flag,
      reflection: parsed.reflection || "",
      content,
      istighfar,
    }),
    { headers: { ...CORS_HEADERS, "Content-Type": "application/json" } },
  );
});
